#!/usr/bin/env python3
"""
Correct workflow for Method 4 personalization:
1. Load generic ProMPs from generic_library (generated by ProMP_basic.py)
2. Use identified style from PCA/ANOVA results to personalize generic ProMPs
3. Compare personalized generic ProMPs with User 1's original trajectories
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Tuple

import numpy as np

# Set matplotlib backend
import os
_root_dir = Path(__file__).resolve().parent
_mpl_cache = _root_dir / ".mplcache"
_cache_home = _root_dir / ".cache"
os.environ.setdefault("MPLCONFIGDIR", str(_mpl_cache))
os.environ.setdefault("XDG_CACHE_HOME", str(_cache_home))
os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from scipy.spatial.distance import cdist

np.seterr(all="ignore")


def read_trajectory_csv(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Read trajectory CSV file and return time and y coordinates."""
    data = np.genfromtxt(path, delimiter=",", skip_header=1).astype(float)
    if data.ndim == 1 or data.shape[1] < 3:
        raise ValueError(f"Expected CSV columns time,x,y in {path}")
    data = data[np.isfinite(data).all(axis=1)]
    time = data[:, 0]
    y = data[:, 1:3]
    return time, y


def infer_task_id_from_path(csv_path: Path) -> str:
    """Extract task ID from folder structure (e.g., task_a -> a)."""
    parts = csv_path.parts
    for part in parts:
        if part.startswith("task_"):
            return part.replace("task_", "")
    return "unknown"


def infer_user_id_from_path(csv_path: Path) -> str:
    """Extract user ID from folder structure (e.g., User_1 -> 1)."""
    parts = csv_path.parts
    for part in parts:
        if part.startswith("User_"):
            return part.replace("User_", "")
    return "unknown"


def normalize_time(time: np.ndarray) -> np.ndarray:
    """Normalize time to [0, 1] range."""
    t0 = float(time[0])
    t1 = float(time[-1])
    if t1 <= t0:
        return np.linspace(0.0, 1.0, num=time.shape[0])
    return (time - t0) / (t1 - t0)


def make_rbf_basis(t: np.ndarray, n_basis: int, width: float) -> np.ndarray:
    """Create RBF basis functions."""
    centers = np.linspace(0.0, 1.0, num=n_basis)
    diff = t[:, None] - centers[None, :]
    basis = np.exp(-0.5 * (diff / width) ** 2)
    basis /= basis.sum(axis=1, keepdims=True)
    return basis


def fit_weights(
    time: np.ndarray, y: np.ndarray, n_basis: int, width: float, ridge: float
) -> np.ndarray:
    """Fit ProMP weights from trajectory data."""
    t_norm = normalize_time(time)
    phi = make_rbf_basis(t_norm, n_basis, width)
    k = phi.shape[1]
    d = y.shape[1]
    weights = np.zeros((d, k))
    a = phi.T @ phi + ridge * np.eye(k)
    for dim in range(d):
        b = phi.T @ y[:, dim]
        weights[dim] = np.linalg.solve(a, b)
    return weights.reshape(-1)


def get_style_components(anova_file: Path, style_labels: List[str] = None) -> List[int]:
    """Get style component indices from ANOVA results."""
    if style_labels is None:
        style_labels = ['style', 'style_candidate']
    
    with anova_file.open('r') as f:
        anova_data = json.load(f)
    
    style_components = []
    for result in anova_data['results']:
        if result['label'] in style_labels:
            style_components.append(result['component'] - 1)  # 0-indexed
    
    return sorted(style_components)


def compute_style_coordinates(
    target_weights: np.ndarray,
    pca_mean: np.ndarray,
    pca_eigvecs: np.ndarray,
    style_component_indices: List[int]
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Compute style coordinates for target user's weights.
    
    Returns:
        style_coordinates: (N, d_s) - style coordinates for each weight
        style_mean: (d_s,) - average style coordinates
        V_s: (P, d_s) - style subspace basis
    """
    if len(style_component_indices) == 0:
        return np.zeros((target_weights.shape[0], 0)), np.zeros(0), np.zeros((target_weights.shape[1], 0))
    
    V_s = pca_eigvecs[:, style_component_indices]  # (P, d_s)
    centered_weights = target_weights - pca_mean  # (N, P)
    style_coordinates = centered_weights @ V_s  # (N, d_s)
    style_mean = np.mean(style_coordinates, axis=0)  # (d_s,)
    
    return style_coordinates, style_mean, V_s


def method4_style_in_covariance(
    generic_means: dict,
    generic_covs: dict,
    style_mean: np.ndarray,
    V_s: np.ndarray,
    style_cov_scale: float = 0.1,
    aggressiveness: float = 1.0
) -> Tuple[dict, dict]:
    """
    Method 4: Modify both mean and covariance based on style.
    
    With aggressiveness parameter:
    μ_k^styled = μ_k + aggressiveness * V_s * z̄^(s)
    Σ_k^styled = Σ_k + aggressiveness * style_cov_scale * V_s * V_s^T
    
    Args:
        aggressiveness: Scale factor for personalization strength (>1.0 = more aggressive)
    """
    style_offset = aggressiveness * (V_s @ style_mean)
    style_cov_addition = aggressiveness * style_cov_scale * (V_s @ V_s.T)
    
    personalized_means = {}
    personalized_covs = {}
    for task, mean in generic_means.items():
        personalized_means[task] = mean + style_offset
        personalized_covs[task] = generic_covs[task] + style_cov_addition
    
    return personalized_means, personalized_covs


def reconstruct_trajectory(weights: np.ndarray, n_basis: int = 20, width: float = 0.05, 
                          duration: float = 1.0, dt: float = 0.01) -> np.ndarray:
    """Reconstruct trajectory from ProMP weights."""
    d = 2
    weights_2d = weights.reshape(d, n_basis)
    t = np.arange(0, duration, dt)
    t_norm = t / duration
    centers = np.linspace(0.0, 1.0, num=n_basis)
    diff = t_norm[:, None] - centers[None, :]
    basis = np.exp(-0.5 * (diff / width) ** 2)
    basis /= basis.sum(axis=1, keepdims=True)
    trajectory = basis @ weights_2d.T
    return trajectory


def interpolate_trajectory(traj: np.ndarray, target_length: int) -> np.ndarray:
    """Interpolate trajectory to target length."""
    if len(traj) == target_length:
        return traj
    original_indices = np.linspace(0, len(traj) - 1, len(traj))
    target_indices = np.linspace(0, len(traj) - 1, target_length)
    interp_func = interp1d(original_indices, traj, axis=0, kind='linear', 
                          bounds_error=False, fill_value='extrapolate')
    return interp_func(target_indices)


def calculate_l2_norm(traj1: np.ndarray, traj2: np.ndarray) -> float:
    """Calculate L2-norm between two trajectories."""
    max_length = max(len(traj1), len(traj2))
    traj1_interp = interpolate_trajectory(traj1, max_length)
    traj2_interp = interpolate_trajectory(traj2, max_length)
    diff = traj1_interp - traj2_interp
    return float(np.sqrt(np.sum(diff ** 2)))


def calculate_trajectory_iou(traj1: np.ndarray, traj2: np.ndarray, threshold: float = 5.0) -> float:
    """Calculate IoU between two trajectories."""
    max_length = max(len(traj1), len(traj2))
    traj1_interp = interpolate_trajectory(traj1, max_length)
    traj2_interp = interpolate_trajectory(traj2, max_length)
    distances = cdist(traj1_interp, traj2_interp)
    min_distances_traj1 = np.min(distances, axis=1)
    matches_traj1 = (min_distances_traj1 <= threshold).sum()
    min_distances_traj2 = np.min(distances, axis=0)
    matches_traj2 = (min_distances_traj2 <= threshold).sum()
    intersection = (matches_traj1 + matches_traj2) / 2.0
    union = max_length
    if union == 0:
        return 0.0
    return float(intersection / union)


def main():
    parser = argparse.ArgumentParser(description="Personalize generic library with Method 4 and evaluate.")
    parser.add_argument(
        "--generic_library",
        type=str,
        default="generic_library",
        help="Path to generic library directory (from ProMP_basic.py).",
    )
    parser.add_argument(
        "--pca_results",
        type=str,
        default="ProMP/promp_pca_results.npz",
        help="Path to PCA results.",
    )
    parser.add_argument(
        "--anova_results",
        type=str,
        default="ProMP/style_anova_results.json",
        help="Path to ANOVA results.",
    )
    parser.add_argument(
        "--target_user",
        type=str,
        default="1",
        help="Target user ID for personalization.",
    )
    parser.add_argument(
        "--trajectories_dir",
        type=str,
        default="output",
        help="Directory containing target user's trajectory CSVs.",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default="ProMP/vis",
        help="Output directory for plots.",
    )
    parser.add_argument(
        "--task_b",
        type=str,
        default="b",
        help="Task ID for detailed trajectory plot.",
    )
    parser.add_argument("--n_basis", type=int, default=20, help="RBF basis count.")
    parser.add_argument("--width", type=float, default=0.05, help="RBF width.")
    parser.add_argument("--ridge", type=float, default=1e-6, help="Ridge regularizer.")
    parser.add_argument("--dt", type=float, default=0.01, help="Time step.")
    parser.add_argument(
        "--style_cov_scale",
        type=float,
        default=0.1,
        help="Scale factor for style covariance addition (Method 4).",
    )
    parser.add_argument(
        "--aggressiveness",
        type=float,
        default=1.0,
        help="Aggressiveness factor for personalization (>1.0 = more aggressive, <1.0 = more conservative).",
    )
    parser.add_argument(
        "--iou_threshold",
        type=float,
        default=5.0,
        help="Distance threshold for IoU calculation.",
    )
    args = parser.parse_args()
    
    generic_library_dir = Path(args.generic_library)
    pca_file = Path(args.pca_results)
    anova_file = Path(args.anova_results)
    trajectories_dir = Path(args.trajectories_dir)
    output_dir = Path(args.out_dir)
    target_user_id = args.target_user
    
    print("="*60)
    print("CORRECT WORKFLOW: Personalize Generic Library with Method 4")
    print("="*60)
    
    # Step 1: Load generic ProMPs from generic_library
    print("\nStep 1: Loading generic ProMPs from generic_library...")
    generic_tasks = sorted([d.name.replace("task_", "").replace("_initialpromp", "") 
                          for d in generic_library_dir.iterdir() 
                          if d.is_dir() and d.name.endswith("_initialpromp")])
    
    generic_means = {}
    generic_covs = {}
    for task in generic_tasks:
        promp_file = generic_library_dir / f"task_{task}_initialpromp" / "promp.npz"
        if promp_file.exists():
            promp_data = np.load(promp_file)
            generic_means[task] = promp_data['mean']
            generic_covs[task] = promp_data['cov']
    
    print(f"Loaded {len(generic_means)} generic ProMPs")
    
    # Step 2: Load PCA and ANOVA results to get style components
    print("\nStep 2: Loading PCA and ANOVA results...")
    pca_data = np.load(pca_file)
    pca_mean = pca_data['mean']
    pca_eigvecs = pca_data['eigvecs']
    
    style_indices = get_style_components(anova_file)
    print(f"Found {len(style_indices)} style components: {[i+1 for i in style_indices]}")
    
    # Step 3: Load target user's trajectories and compute style offset
    print(f"\nStep 3: Loading target user {target_user_id} trajectories...")
    target_weights = []
    target_tasks = []
    for csv_path in trajectories_dir.rglob("*-trajectory.csv"):
        user_id = infer_user_id_from_path(csv_path)
        if user_id == target_user_id:
            try:
                time, y = read_trajectory_csv(csv_path)
                if time.size < 2:
                    continue
                task_id = infer_task_id_from_path(csv_path)
                w = fit_weights(time, y, args.n_basis, args.width, args.ridge)
                target_weights.append(w)
                target_tasks.append(task_id)
            except Exception as e:
                print(f"Warning: Skipping {csv_path}: {e}")
                continue
    
    if len(target_weights) == 0:
        raise ValueError(f"No trajectories found for user {target_user_id}")
    
    target_weights_arr = np.vstack(target_weights)
    print(f"Loaded {len(target_weights)} trajectories from user {target_user_id}")
    
    # Compute style coordinates
    style_coords, style_mean, V_s = compute_style_coordinates(
        target_weights_arr, pca_mean, pca_eigvecs, style_indices
    )
    print(f"Style mean: {style_mean}")
    print(f"Style offset norm: {np.linalg.norm(V_s @ style_mean):.4f}")
    
    # Step 4: Apply Method 4 to personalize generic ProMPs
    print(f"\nStep 4: Applying Method 4 (Style in Covariance) to personalize generic ProMPs...")
    print(f"  Aggressiveness: {args.aggressiveness}x")
    print(f"  Style covariance scale: {args.style_cov_scale}")
    personalized_means, personalized_covs = method4_style_in_covariance(
        generic_means, generic_covs, style_mean, V_s, args.style_cov_scale, args.aggressiveness
    )
    print(f"Personalized {len(personalized_means)} ProMPs")
    
    # Step 5: Compare with User 1's original trajectories
    print("\nStep 5: Comparing with User 1's original trajectories...")
    user1_trajectories = {}
    for csv_path in trajectories_dir.rglob("*-trajectory.csv"):
        user_id = infer_user_id_from_path(csv_path)
        if user_id == target_user_id:
            try:
                time, y = read_trajectory_csv(csv_path)
                if time.size < 2:
                    continue
                task_id = infer_task_id_from_path(csv_path)
                user1_trajectories[task_id] = y
            except Exception as e:
                continue
    
    print(f"Loaded {len(user1_trajectories)} User 1 trajectories for comparison")
    
    # Process tasks that User 1 has
    l2_norms_generic = []
    l2_norms_method4 = []
    iou_generic = []
    iou_method4 = []
    task_labels = []
    
    for task in sorted(generic_tasks):
        if task not in user1_trajectories:
            continue
        if task not in personalized_means:
            continue
        
        task_labels.append(task)
        user1_traj = user1_trajectories[task]
        generic_mean = generic_means[task]
        method4_mean = personalized_means[task]
        
        # Reconstruct trajectories
        duration = len(user1_traj) * args.dt
        generic_traj = reconstruct_trajectory(generic_mean, args.n_basis, args.width, duration, args.dt)
        method4_traj = reconstruct_trajectory(method4_mean, args.n_basis, args.width, duration, args.dt)
        
        # Interpolate to match User 1 trajectory length
        if len(generic_traj) != len(user1_traj):
            generic_traj = interpolate_trajectory(generic_traj, len(user1_traj))
        if len(method4_traj) != len(user1_traj):
            method4_traj = interpolate_trajectory(method4_traj, len(user1_traj))
        
        # Calculate metrics
        l2_gen = calculate_l2_norm(user1_traj, generic_traj)
        l2_m4 = calculate_l2_norm(user1_traj, method4_traj)
        iou_gen = calculate_trajectory_iou(user1_traj, generic_traj, args.iou_threshold)
        iou_m4 = calculate_trajectory_iou(user1_traj, method4_traj, args.iou_threshold)
        
        l2_norms_generic.append(l2_gen)
        l2_norms_method4.append(l2_m4)
        iou_generic.append(iou_gen)
        iou_method4.append(iou_m4)
        
        print(f"  Task {task}: L2 (gen={l2_gen:.2f}, m4={l2_m4:.2f}), IoU (gen={iou_gen:.3f}, m4={iou_m4:.3f})")
    
    # Create plots
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Plot 1: L2-norm comparison
    print("\nCreating L2-norm comparison plot...")
    fig1, ax1 = plt.subplots(figsize=(14, 8))
    x_pos = np.arange(len(task_labels))
    width_bar = 0.35
    
    bars1 = ax1.bar(x_pos - width_bar/2, l2_norms_generic, width_bar, 
                   label='User 1 Original vs Generic ProMP', alpha=0.8, 
                   color='blue', edgecolor='black', linewidth=1)
    bars2 = ax1.bar(x_pos + width_bar/2, l2_norms_method4, width_bar, 
                   label='User 1 Original vs Method 4 Personalized', alpha=0.8, 
                   color='red', edgecolor='black', linewidth=1)
    
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.1f}', ha='center', va='bottom', fontsize=8, fontweight='bold')
    
    ax1.set_xlabel('Task', fontsize=14, fontweight='bold')
    ax1.set_ylabel('L2-norm', fontsize=14, fontweight='bold')
    ax1.set_title('L2-norm Comparison: Generic ProMP vs Method 4 Personalized (from Generic Library)', 
                 fontsize=16, fontweight='bold', pad=15)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(task_labels, rotation=45, ha='right', fontsize=11)
    ax1.legend(fontsize=12, loc='upper left')
    ax1.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    avg_l2_gen = np.mean(l2_norms_generic)
    avg_l2_m4 = np.mean(l2_norms_method4)
    improvement_l2 = ((avg_l2_gen - avg_l2_m4) / avg_l2_gen * 100) if avg_l2_gen > 0 else 0
    
    stats_text = f'Average L2-norm:\nGeneric: {avg_l2_gen:.2f}\nMethod 4: {avg_l2_m4:.2f}\n'
    if improvement_l2 > 0:
        stats_text += f'Improvement: {improvement_l2:.1f}%'
    else:
        stats_text += f'Change: {improvement_l2:.1f}%'
    
    ax1.text(0.02, 0.98, stats_text, transform=ax1.transAxes, fontsize=11,
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))
    
    plt.tight_layout()
    l2_plot_file = output_dir / "method4_correct_l2_norm.png"
    plt.savefig(l2_plot_file, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"L2-norm plot saved to: {l2_plot_file}")
    
    # Plot 2: IoU comparison
    print("Creating IoU comparison plot...")
    fig2, ax2 = plt.subplots(figsize=(14, 8))
    
    bars3 = ax2.bar(x_pos - width_bar/2, iou_generic, width_bar, 
                   label='User 1 Original vs Generic ProMP', alpha=0.8, 
                   color='blue', edgecolor='black', linewidth=1)
    bars4 = ax2.bar(x_pos + width_bar/2, iou_method4, width_bar, 
                   label='User 1 Original vs Method 4 Personalized', alpha=0.8, 
                   color='red', edgecolor='black', linewidth=1)
    
    for bars in [bars3, bars4]:
        for bar in bars:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.3f}', ha='center', va='bottom', fontsize=8, fontweight='bold')
    
    ax2.set_xlabel('Task', fontsize=14, fontweight='bold')
    ax2.set_ylabel('IoU (Intersection over Union)', fontsize=14, fontweight='bold')
    ax2.set_title(f'IoU Comparison: Generic ProMP vs Method 4 Personalized (threshold={args.iou_threshold})', 
                 fontsize=16, fontweight='bold', pad=15)
    ax2.set_xticks(x_pos)
    ax2.set_xticklabels(task_labels, rotation=45, ha='right', fontsize=11)
    ax2.set_ylim([0, 1.1])
    ax2.legend(fontsize=12, loc='upper left')
    ax2.grid(True, alpha=0.3, axis='y', linestyle='--')
    
    avg_iou_gen = np.mean(iou_generic)
    avg_iou_m4 = np.mean(iou_method4)
    improvement_iou = ((avg_iou_m4 - avg_iou_gen) / avg_iou_gen * 100) if avg_iou_gen > 0 else 0
    
    stats_text = f'Average IoU:\nGeneric: {avg_iou_gen:.3f}\nMethod 4: {avg_iou_m4:.3f}\n'
    if improvement_iou > 0:
        stats_text += f'Improvement: {improvement_iou:.1f}%'
    else:
        stats_text += f'Change: {improvement_iou:.1f}%'
    
    ax2.text(0.02, 0.98, stats_text, transform=ax2.transAxes, fontsize=11,
            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))
    
    plt.tight_layout()
    iou_plot_file = output_dir / "method4_correct_iou.png"
    plt.savefig(iou_plot_file, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"IoU plot saved to: {iou_plot_file}")
    
    # Plot 3: Detailed trajectory for task b
    print(f"\nCreating detailed trajectory plot for task {args.task_b}...")
    
    if args.task_b not in user1_trajectories or args.task_b not in personalized_means:
        print(f"Warning: Task {args.task_b} not available")
    else:
        user1_traj_b = user1_trajectories[args.task_b]
        generic_mean_b = generic_means[args.task_b]
        method4_mean_b = personalized_means[args.task_b]
        
        duration_b = len(user1_traj_b) * args.dt
        generic_traj_b = reconstruct_trajectory(generic_mean_b, args.n_basis, args.width, duration_b, args.dt)
        method4_traj_b = reconstruct_trajectory(method4_mean_b, args.n_basis, args.width, duration_b, args.dt)
        
        if len(generic_traj_b) != len(user1_traj_b):
            generic_traj_b = interpolate_trajectory(generic_traj_b, len(user1_traj_b))
        if len(method4_traj_b) != len(user1_traj_b):
            method4_traj_b = interpolate_trajectory(method4_traj_b, len(user1_traj_b))
        
        l2_gen_b = calculate_l2_norm(user1_traj_b, generic_traj_b)
        l2_m4_b = calculate_l2_norm(user1_traj_b, method4_traj_b)
        iou_gen_b = calculate_trajectory_iou(user1_traj_b, generic_traj_b, args.iou_threshold)
        iou_m4_b = calculate_trajectory_iou(user1_traj_b, method4_traj_b, args.iou_threshold)
        
        fig3, ax3 = plt.subplots(figsize=(10, 8))
        
        ax3.plot(user1_traj_b[:, 0], user1_traj_b[:, 1], 
                'k-', linewidth=4, label='Original (User 1)', alpha=0.9, zorder=3)
        ax3.plot(generic_traj_b[:, 0], generic_traj_b[:, 1], 
                'b:', linewidth=3, label='Generic ProMP', alpha=0.8, zorder=2)
        ax3.plot(method4_traj_b[:, 0], method4_traj_b[:, 1], 
                'r--', linewidth=3, label='Method 4 Personalized', alpha=0.8, zorder=2)
        
        ax3.plot(user1_traj_b[0, 0], user1_traj_b[0, 1], 
                'go', markersize=15, label='Start', zorder=5, 
                markeredgecolor='black', markeredgewidth=2)
        ax3.plot(user1_traj_b[-1, 0], user1_traj_b[-1, 1], 
                'ks', markersize=15, label='End (Original)', zorder=5, 
                markeredgecolor='white', markeredgewidth=2)
        ax3.plot(generic_traj_b[-1, 0], generic_traj_b[-1, 1], 
                'bs', markersize=12, label='End (Generic)', zorder=4, 
                markeredgecolor='white', markeredgewidth=1.5)
        ax3.plot(method4_traj_b[-1, 0], method4_traj_b[-1, 1], 
                'rs', markersize=12, label='End (Method 4)', zorder=4, 
                markeredgecolor='white', markeredgewidth=1.5)
        
        ax3.set_xlabel('X Position', fontsize=12, fontweight='bold')
        ax3.set_ylabel('Y Position', fontsize=12, fontweight='bold')
        ax3.set_title(f'Detailed Trajectory: Task {args.task_b.upper()}\n'
                     f'Method 4 (Style in Covariance) from Generic Library\n'
                     f'L2: Generic={l2_gen_b:.2f}, Method 4={l2_m4_b:.2f} | '
                     f'IoU: Generic={iou_gen_b:.3f}, Method 4={iou_m4_b:.3f}',
                     fontsize=14, fontweight='bold', pad=15)
        ax3.legend(fontsize=11, loc='best', framealpha=0.9)
        ax3.grid(True, alpha=0.3, linestyle='--')
        ax3.set_aspect('equal')
        
        plt.tight_layout()
        detail_plot_file = output_dir / f"method4_correct_detailed_task_{args.task_b}.png"
        plt.savefig(detail_plot_file, dpi=200, bbox_inches='tight')
        plt.close()
        print(f"Detailed trajectory plot saved to: {detail_plot_file}")
    
    # Print summary
    print("\n" + "="*60)
    print("METHOD 4 EVALUATION SUMMARY (CORRECT WORKFLOW)")
    print("="*60)
    print(f"Tasks compared: {len(task_labels)}")
    print(f"Average L2-norm - Generic: {avg_l2_gen:.4f}, Method 4: {avg_l2_m4:.4f}")
    print(f"Average IoU - Generic: {avg_iou_gen:.4f}, Method 4: {avg_iou_m4:.4f}")
    print(f"L2-norm improvement: {improvement_l2:.2f}%")
    print(f"IoU improvement: {improvement_iou:.2f}%")


if __name__ == "__main__":
    main()
